hydra:
  launcher:
    timeout_min: 360
    cpus_per_task: 16
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 64
    name: ${hydra.job.name}
    partition: gpu
    array_parallelism: 4

defaults:
  - override hydra/launcher: submitit_slurm